"""
patcher.py — Applies an AI-generated patch, commits it, and pushes a new branch.

Branch naming convention:
    autoverif/fix-{short_sha}-{unix_timestamp}

Steps
-----
1. Create and checkout a new branch from the current HEAD.
2. Write the patch content to a temp file.
3. Apply with ``git apply``.
4. Stage all changes (``git add -A``).
5. Commit with a descriptive message.
6. Push the new branch to ``origin``.
7. Clean up the temp file.

All git operations are done via ``subprocess`` rather than GitPython so that
the user's configured git credentials / SSH agent are used transparently.
"""

from __future__ import annotations

import subprocess
import tempfile
import time
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console(stderr=True)

# Maximum time (seconds) for any single git subprocess call.
_GIT_TIMEOUT = 120


class PatchError(Exception):
    """Raised when the patch cannot be applied."""


class Patcher:
    """
    Applies a unified-diff patch inside a git repository and pushes the result
    to a new branch on the remote.
    """

    def __init__(
        self,
        repo_path: str,
        patch_content: str,
        commit_sha: str,
    ) -> None:
        self.repo_path = Path(repo_path).resolve()
        self.patch_content = patch_content
        self.commit_sha = commit_sha
        self.short_sha = commit_sha[:8] if commit_sha else "unknown"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def apply(self) -> str:
        """
        Apply the patch and push to a new branch.

        Returns:
            The name of the newly created and pushed branch.

        Raises:
            PatchError: if ``git apply`` fails.
            subprocess.CalledProcessError: for unexpected git errors.
        """
        self._validate_repo()

        branch_name = self._make_branch_name()
        console.log(f"[cyan]Creating branch:[/cyan] {branch_name}")
        self._git("checkout", "-b", branch_name)

        patch_file: Optional[Path] = None
        try:
            patch_file = self._write_patch_file()
            self._apply_patch(patch_file)
            self._stage_all()
            self._commit(branch_name)
            self._push(branch_name)
        finally:
            if patch_file and patch_file.exists():
                patch_file.unlink(missing_ok=True)

        console.log(f"[green]Branch pushed:[/green] {branch_name}")
        return branch_name

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _validate_repo(self) -> None:
        if not self.repo_path.is_dir():
            raise NotADirectoryError(f"repo_path does not exist: {self.repo_path}")
        git_dir = self.repo_path / ".git"
        if not git_dir.exists():
            raise ValueError(
                f"{self.repo_path} is not a git repository (no .git directory)."
            )

    def _make_branch_name(self) -> str:
        timestamp = int(time.time())
        return f"autoverif/fix-{self.short_sha}-{timestamp}"

    def _write_patch_file(self) -> Path:
        """Write patch_content to a temporary file and return its path."""
        fd, tmp_path = tempfile.mkstemp(suffix=".patch", prefix="autoverif_")
        import os
        os.close(fd)
        patch_file = Path(tmp_path)
        patch_file.write_text(self.patch_content, encoding="utf-8")
        console.log(f"[dim]Patch written to temp file: {patch_file}[/dim]")
        return patch_file

    def _apply_patch(self, patch_file: Path) -> None:
        """Run git apply; on failure, raise PatchError with stderr detail."""
        result = self._git_capture("apply", "--whitespace=fix", str(patch_file))
        if result.returncode != 0:
            stderr = result.stderr.decode("utf-8", errors="replace")
            raise PatchError(
                f"git apply failed (exit {result.returncode}):\n{stderr}"
            )
        console.log("[green]Patch applied successfully[/green]")

    def _stage_all(self) -> None:
        self._git("add", "-A")
        console.log("[dim]Staged all changes[/dim]")

    def _commit(self, branch_name: str) -> None:
        message = (
            f"AutoVerif AI: auto-fix for {self.commit_sha}\n\n"
            f"Applied on branch: {branch_name}\n"
            "Generated by AutoVerif AI — review before merging."
        )
        self._git("commit", "-m", message)
        console.log("[dim]Committed changes[/dim]")

    def _push(self, branch_name: str) -> None:
        console.log(f"[cyan]Pushing[/cyan] {branch_name} to origin …")
        self._git("push", "--set-upstream", "origin", branch_name)

    # ------------------------------------------------------------------
    # Git subprocess wrappers
    # ------------------------------------------------------------------

    def _git(self, *args: str) -> None:
        """Run a git command, raising CalledProcessError on non-zero exit."""
        subprocess.run(
            ["git", *args],
            cwd=str(self.repo_path),
            check=True,
            timeout=_GIT_TIMEOUT,
        )

    def _git_capture(self, *args: str) -> subprocess.CompletedProcess:
        """Run git, capture output, do NOT raise on non-zero exit."""
        return subprocess.run(
            ["git", *args],
            cwd=str(self.repo_path),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=_GIT_TIMEOUT,
        )
